overworld1-x: 0
overworld1-y: 0
overworld1-z: 0
overworld2-x: 0
overworld2-y: 0
overworld2-z: 0
overworld3-x: 0
overworld3-y: 0
overworld3-z: 0

desert1-x: 0
desert1-y: 0
desert1-z: 0
desert2-x: 0
desert2-y: 0
desert2-z: 0
desert3-x: 0
desert3-y: 0
desert3-z: 0

ocean1-x: 0
ocean1-y: 0
ocean1-z: 0
ocean2-x: 0
ocean2-y: 0
ocean2-z: 0
ocean3-x: 0
ocean3-y: 0
ocean3-z: 0

jungle1-x: 0
jungle1-y: 0
jungle1-z: 0
jungle2-x: 0
jungle2-y: 0
jungle2-z: 0
jungle3-x: 0
jungle3-y: 0
jungle3-z: 0

city1-x: 0
city1-y: 0
city1-z: 0
city2-x: 0
city2-y: 0
city2-z: 0
city3-x: 0
city3-y: 0
city3-z: 0

alien1-x: 0
alien1-y: 0
alien1-z: 0
alien1-x: 0
alien1-y: 0
alien1-z: 0
alien1-x: 0
alien1-y: 0
alien1-z: 0
